# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_addressbook_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(default='', max_length=210),
        ),
    ]
