# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateTimeField(),
        ),
    ]
